#!/usr/bin/env python3
"""
WebXPDF - HTML to PDF Converter
Usage:
  python webxpdf.py <html_file.html> [output.pdf]
  python webxpdf.py "<h1>Hello</h1><p>World</p>" output.pdf
"""

import sys
import os
from fpdf import FPDF
from bs4 import BeautifulSoup

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by WebXPDF', 0, 1, 'R')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def html_to_pdf(html_content, output_file):
    soup = BeautifulSoup(html_content, 'html.parser')
    
    for element in soup(["script", "style"]):
        element.decompose()
    
    title = soup.title.string if soup.title else "Document"
    title = title.replace('\n', ' ').strip()
    
    pdf = PDF()
    pdf.add_page()
    
    pdf.set_font('Arial', 'B', 16)
    pdf.multi_cell(0, 10, title)
    pdf.ln(5)
    
    pdf.set_font('Arial', '', 12)
    for element in soup.find_all(['h1', 'h2', 'h3', 'p', 'li']):
        text = element.get_text(separator=' ', strip=True)
        if not text:
            continue
            
        if element.name == 'h1':
            pdf.set_font('Arial', 'B', 16)
            pdf.multi_cell(0, 10, text)
        elif element.name == 'h2':
            pdf.set_font('Arial', 'B', 14)
            pdf.multi_cell(0, 10, text)
        elif element.name == 'h3':
            pdf.set_font('Arial', 'B', 12)
            pdf.multi_cell(0, 10, text)
        elif element.name == 'li':
            pdf.set_font('Arial', '', 12)
            pdf.multi_cell(0, 8, f"  • {text}")
        else:
            pdf.set_font('Arial', '', 12)
            pdf.multi_cell(0, 8, text)
        
        pdf.ln(2)
    
    pdf.output(output_file)
    return os.path.abspath(output_file)

def main():
    print("🚀 WebXPDF - HTML to PDF Converter")
    print("=" * 50)
    
    if len(sys.argv) < 2:
        print("\n❌ Error: Missing input!")
        print("\nUsage:")
        print("  python webxpdf.py <html_file.html> [output.pdf]")
        print("  python webxpdf.py \"<h1>Hello</h1>\" output.pdf")
        print("\nExamples:")
        print("  python webxpdf.py article.html")
        print("  python webxpdf.py article.html my_article.pdf")
        print("  python webxpdf.py \"<h1>Test</h1><p>Content</p>\" test.pdf")
        return
    
    input_arg = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "output.pdf"
    
    if not output_file.endswith('.pdf'):
        output_file += '.pdf'
    
    if os.path.isfile(input_arg):
        print(f"📄 Reading HTML from file: {input_arg}")
        with open(input_arg, 'r', encoding='utf-8') as f:
            html_content = f.read()
    else:
        print("📝 Using provided HTML code")
        html_content = input_arg
    
    print(f"💾 Output file: {output_file}")
    print("⏳ Converting...")
    
    try:
        abs_path = html_to_pdf(html_content, output_file)
        print("=" * 50)
        print(f"✅ SUCCESS! PDF created.")
        print(f"📁 Location: {abs_path}")
        print(f"💡 Tip: Type 'termux-open {abs_path}' to view it!")
    except Exception as e:
        print("=" * 50)
        print(f"❌ FAILED to convert.")
        print(f"Error: {e}")

if __name__ == "__main__":
    main()
